src/integration-test/resources/EmployeeChecklistIT/__files/test11_updateAllTasksInPhase/request.json
src/integration-test/resources/EmployeeChecklistIT/__files/test12_updateCommonTaskFulfilment/request.json
src/integration-test/resources/EmployeeChecklistIT/__files/test13_updateCustomTaskFulfilment/request.json
src/main/java/se/sundsvall/checklist/api/model/EmployeeChecklistPhaseUpdateRequest.java
src/main/java/se/sundsvall/checklist/api/model/EmployeeChecklistTask.java
src/main/java/se/sundsvall/checklist/api/model/EmployeeChecklistTaskUpdateRequest.java
src/main/java/se/sundsvall/checklist/api/model/OrganizationCreateRequest.java
src/main/java/se/sundsvall/checklist/api/validation/ValidChannels.java
src/main/java/se/sundsvall/checklist/api/validation/impl/ValidChannelsConstraintValidator.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/PortingService.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/api/model/EmployeeChecklistPhaseUpdateRequestTest.java
src/test/java/se/sundsvall/checklist/api/model/EmployeeChecklistTaskTest.java
src/test/java/se/sundsvall/checklist/api/model/EmployeeChecklistTaskUpdateRequestTest.java
src/test/java/se/sundsvall/checklist/api/validation/impl/ValidChannelsConstraintValidatorTest.java
src/test/resources/api/openapi.yaml

- Added updated by to api for updating task progress
- Corrected validation of valid channels
- Added missing municipality id mapping to porting service
- Fixed bug when updating employee for the first time (and updated field is not initiated with a date)

UF-10761: Added updated by to api for updating task progress

---

src/integration-test/java/apptest/EmployeeChecklistIT.java
src/integration-test/resources/EmployeeChecklistIT/__files/test16_fetchChecklistWithMentorSetAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test17_setMentor/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test17_setMentor/request.json
src/integration-test/resources/sql/employeeChecklistIT-testdata.sql
src/main/java/se/sundsvall/checklist/api/EmployeeChecklistResource.java
src/main/java/se/sundsvall/checklist/api/model/EmployeeChecklist.java
src/main/java/se/sundsvall/checklist/api/model/Mentor.java
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/integration/db/model/EmployeeChecklistEntity.java
src/main/java/se/sundsvall/checklist/integration/db/model/MentorEntity.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/resources/db/migration/V1_3__add_employee_checklist_mentor.sql
src/test/java/se/sundsvall/checklist/TestObjectFactory.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/api/model/MentorTest.java
src/test/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegrationTest.java
src/test/java/se/sundsvall/checklist/integration/db/model/MentorEntityTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/resources/api/openapi.yaml
src/test/resources/db/schema/schema.sql

Adds a mentor object, holding user id and name, to employee checklists.

UF-10671 - Add mentor to employee checklists

---

src/integration-test/resources/DelegationIT/__files/test2_fetchDelegatedEmployeeChecklists/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test01_fetchChecklistAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test02_fetchChecklistAsEmployeeWhenManagerChanged/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test03_fetchChecklistsAsManager/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test16_fetchChecklistWithMentorSetAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test17_setMentor/expected.json
src/main/java/se/sundsvall/checklist/api/model/Stakeholder.java
src/main/java/se/sundsvall/checklist/service/mapper/OrganizationMapper.java
src/test/java/se/sundsvall/checklist/service/mapper/OrganizationMapperTest.java
src/test/resources/api/openapi.yaml

UF-11066: Added attribute for job title to api response

---

src/main/java/se/sundsvall/checklist/integration/db/model/SortorderEntity.java
src/main/java/se/sundsvall/checklist/integration/db/model/enums/ComponentType.java
src/main/java/se/sundsvall/checklist/integration/db/repository/SortorderRepository.java
src/main/resources/db/migration/V1_1__add_custom_sortorder_table.sql
src/test/java/se/sundsvall/checklist/integration/db/model/SortorderEntityTest.java
src/test/java/se/sundsvall/checklist/integration/db/model/enums/ComponentTypeTest.java
src/test/java/se/sundsvall/checklist/integration/db/repository/SortorderRepositoryTest.java
src/test/resources/db/schema/schema.sql
src/test/resources/db/scripts/testdata-junit.sql
src/test/resources/db/scripts/truncate.sql

UF-11080: Added custom sort for checklist components to database model

---

src/main/java/se/sundsvall/checklist/api/CustomSortResource.java
src/main/java/se/sundsvall/checklist/api/model/SortorderRequest.java
src/test/java/se/sundsvall/checklist/TestObjectFactory.java
src/test/java/se/sundsvall/checklist/api/CustomSortResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/CustomSortResourceTest.java
src/test/java/se/sundsvall/checklist/api/model/SortorderRequestTest.java
src/test/resources/api/openapi.yaml

- Added resource to support custom sort order connected to a specific organizational unit

UF-11087: Added resource for saving custom sort order

---

src/integration-test/resources/EmployeeChecklistIT/__files/test14_initializeEmployeeChecklists/mappings/api-employee-new-employments.json
src/main/java/se/sundsvall/checklist/integration/employee/EmployeeFilterBuilder.java
src/test/java/se/sundsvall/checklist/integration/employee/EmployeeFilterBuilderTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java

Updates the filter for getting new employees from the employee API.

UF-10897 - Update filter for fetching new employees

---

pom.xml
src/main/java/se/sundsvall/checklist/configuration/CacheConfiguration.java
src/main/java/se/sundsvall/checklist/integration/mdviewer/MDViewerClient.java
src/main/java/se/sundsvall/checklist/integration/mdviewer/configuration/MDViewerConfiguration.java
src/main/java/se/sundsvall/checklist/integration/mdviewer/configuration/MDViewerProperties.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/contracts/mdviewer/mdviewer.yaml
src/test/java/se/sundsvall/checklist/integration/mdviewer/configuration/MDViewerConfigurationTest.java
src/test/java/se/sundsvall/checklist/integration/mdviewer/configuration/MDViewerPropertiesTest.java

- Added new integration and modified configuration to enable caching of responses from mdviewer service

UF-11081: Added integration to mdviewer service

---

src/main/java/se/sundsvall/checklist/integration/employee/EmployeeClient.java
src/main/java/se/sundsvall/checklist/integration/mdviewer/MDViewerClient.java
src/main/java/se/sundsvall/checklist/integration/messaging/MessagingClient.java
src/main/java/se/sundsvall/checklist/integration/templating/TemplatingClient.java

UF-11348: Added circuit breakers to feign integrations

---

src/integration-test/resources/EmployeeChecklistIT/__files/test14_initializeEmployeeChecklists/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test14_initializeEmployeeChecklists/responses/api-employee-new-employments-response.json
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/java/se/sundsvall/checklist/service/util/VerificationUtils.java
src/test/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegrationTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/java/se/sundsvall/checklist/service/util/VerificationUtilsTest.java

- Added logic for taking event type into consideration upon employee checklist creation
- Refactored to have all verification made in one component instead of having it spread out between several components
- Modified to not take form of employment and event type into consideration when manually initializing a specific employee
- Updated IT-test to include cases where form of employment and event type is not valid for creation of new employee checklist

UF-11548: Added logic for event type

---

pom.xml
src/main/java/se/sundsvall/checklist/integration/employee/configuration/EmployeeProperties.java
src/main/java/se/sundsvall/checklist/integration/eventlog/EventlogClient.java
src/main/java/se/sundsvall/checklist/integration/eventlog/configuration/EventlogConfiguration.java
src/main/java/se/sundsvall/checklist/integration/eventlog/configuration/EventlogProperties.java
src/main/java/se/sundsvall/checklist/integration/mdviewer/configuration/MDViewerProperties.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/contracts/eventlog/eventlog.yaml
src/test/java/se/sundsvall/checklist/integration/eventlog/configuration/EventlogConfigurationTest.java
src/test/java/se/sundsvall/checklist/integration/eventlog/configuration/EventlogPropertiesTest.java

Added Eventlog integration

---

src/integration-test/java/apptest/ChecklistIT.java
src/integration-test/java/apptest/PhaseIT.java
src/integration-test/java/apptest/TaskIT.java
src/main/java/se/sundsvall/checklist/api/model/Checklist.java
src/main/java/se/sundsvall/checklist/service/TaskService.java

- Corrected bug where task did not get deleted
- Extended IT-tests with verifications that items are removed from persistance layer
- Fixed documentation fault

UF-11811: Corrected bug where task did not get deleted

---

src/integration-test/resources/EmployeeChecklistIT/__files/test01_fetchChecklistAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test02_fetchChecklistAsEmployeeWhenManagerChanged/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test03_fetchChecklistsAsManager/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test16_fetchChecklistWithMentorSetAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test19_fetchChecklistWithInheritedSortorder/expected.json
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/service/DelegationService.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/java/se/sundsvall/checklist/service/util/ServiceUtils.java
src/test/java/se/sundsvall/checklist/TestObjectFactory.java
src/test/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegrationTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/java/se/sundsvall/checklist/service/util/ServiceUtilsTest.java

- Adjusted mappers and logic to handle the complete attribute that is stored on the employee checklist entity

UF-11803: Adjusted mappers and logic to handle the complete attribute

---

src/integration-test/resources/EmployeeChecklistIT/__files/test20_fetchOngoingChecklists_1/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test21_fetchOngoingChecklists_2/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test22_fetchOngoingChecklists_3/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test23_fetchOngoingChecklists_4/expected.json
src/main/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepository.java
src/main/java/se/sundsvall/checklist/integration/db/specification/EmployeeChecklistSpecification.java
src/main/java/se/sundsvall/checklist/integration/db/specification/SpecificationBuilder.java
src/test/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepositoryTest.java

- Modified specification to use completed attribute instead of using start and end date

UF-11804: Modified specification to use completed attribute

---

src/main/java/se/sundsvall/checklist/api/EmployeeChecklistResource.java
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/integration/db/model/InitiationInfoEntity.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/scheduler/LockEmployeeChecklistsScheduler.java
src/main/java/se/sundsvall/checklist/service/scheduler/RetrieveNewEmployeesScheduler.java
src/main/java/se/sundsvall/checklist/service/util/VerificationUtils.java
src/main/resources/db/migration/V1_4__add_initiation_info_table.sql
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/integration/db/model/InitiationInfoEntityTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/resources/db/schema/schema.sql

Added new entity, InitiationInfoEntity. Holds information about the latest run of the scheduled initiation task.

UF-14253 Entity for initiation info.

---

src/main/java/se/sundsvall/checklist/integration/db/model/InitiationInfoEntity.java
src/main/java/se/sundsvall/checklist/integration/db/repository/ChecklistRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/CustomTaskRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/DelegateRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/EmployeeRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/InitiationRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/ManagerRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/OrganizationRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/PhaseRepository.java
src/main/java/se/sundsvall/checklist/integration/db/repository/SortorderRepository.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/java/se/sundsvall/checklist/service/scheduler/RetrieveNewEmployeesScheduler.java
src/main/resources/db/migration/V1_5__add_initiation_column.sql
src/test/java/se/sundsvall/checklist/integration/db/model/InitiationInfoEntityTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/java/se/sundsvall/checklist/service/scheduler/RetrieveNewEmployeesSchedulerTest.java
src/test/resources/db/schema/schema.sql

Updated schduled job to save initiationInfo

---

src/integration-test/java/apptest/ChecklistIT.java
src/integration-test/java/apptest/CustomSortorderIT.java
src/integration-test/java/apptest/EmployeeChecklistIT.java
src/integration-test/java/apptest/TaskIT.java
src/integration-test/resources/EmployeeChecklistIT/__files/test25_fetchInitiationInfo/expected.json
src/main/java/se/sundsvall/checklist/api/ChecklistResource.java
src/main/java/se/sundsvall/checklist/api/EmployeeChecklistResource.java
src/main/java/se/sundsvall/checklist/api/TaskResource.java
src/main/java/se/sundsvall/checklist/api/model/InitiationInformation.java
src/main/java/se/sundsvall/checklist/integration/db/repository/InitiationRepository.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/test/java/se/sundsvall/checklist/api/ChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/api/TaskResourceTest.java
src/test/java/se/sundsvall/checklist/api/model/InitiationInformationTest.java
src/test/java/se/sundsvall/checklist/integration/db/repository/InitiationRepositoryTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/resources/api/openapi.yaml
src/test/resources/db/scripts/employeeChecklistIT-testdata.sql
src/test/resources/db/scripts/testdata-junit.sql
src/test/resources/db/scripts/truncate.sql

Uf 14261 add information resource

---

src/integration-test/java/apptest/ChecklistIT.java
src/integration-test/resources/ChecklistIT/__files/test3_createChecklist/mappings/api-service-eventlog.json
src/integration-test/resources/ChecklistIT/__files/test4_createNewVersion/mappings/api-service-eventlog.json
src/integration-test/resources/ChecklistIT/__files/test5_activateChecklist/mappings/api-service-eventlog.json
src/integration-test/resources/ChecklistIT/__files/test6_updateChecklist/mappings/api-service-eventlog.json
src/integration-test/resources/ChecklistIT/__files/test7_deleteChecklist/mappings/api-service-eventlog.json
src/integration-test/resources/CustomSortorderIT/__files/test02_deleteTask/mappings/api-service-eventlog.json
src/integration-test/resources/CustomSortorderIT/__files/test04_deleteChecklist/mappings/api-service-eventlog.json
src/integration-test/resources/TaskIT/__files/test3_createChecklistPhaseTask/mappings/api-service-eventlog.json
src/integration-test/resources/TaskIT/__files/test4_updateChecklistPhaseTask/mappings/api-service-eventlog.json
src/integration-test/resources/TaskIT/__files/test5_deleteChecklistPhaseTask/mappings/api-service-eventlog.json
src/main/java/se/sundsvall/checklist/api/ChecklistResource.java
src/main/java/se/sundsvall/checklist/service/ChecklistService.java
src/main/java/se/sundsvall/checklist/service/EventService.java
src/main/java/se/sundsvall/checklist/service/mapper/OrganizationMapper.java
src/test/java/se/sundsvall/checklist/api/ChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/service/ChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/OrganizationMapperTest.java
src/test/resources/api/openapi.yaml

- Changed setting for communication from EMAIL to NO_COMMUNICATION for disabling email communication when creating new organizational units
- Added logging for activation of checklist and creation of new version of checklist
- Adjusted logging messages

UF-14355: Changed setting to disable email communication by default

---

src/integration-test/resources/EmployeeChecklistIT/__files/shared/responses/api-mdviewer-get-company-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test01_fetchChecklistAsEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test02_fetchChecklistAsEmployeeWhenManagerChanged/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test03_fetchChecklistsAsManager/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test07_createCustomTask/request.json
src/integration-test/resources/EmployeeChecklistIT/__files/test14_initializeEmployeeChecklists/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test16_fetchChecklistWithMentorSetAsEmployee/expected.json
src/main/java/se/sundsvall/checklist/api/model/CustomTaskCreateRequest.java
src/main/java/se/sundsvall/checklist/api/model/CustomTaskUpdateRequest.java
src/main/java/se/sundsvall/checklist/api/validation/RoleTypeSubset.java
src/main/java/se/sundsvall/checklist/api/validation/impl/RoleTypeSubsetConstraintValidator.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/SortorderService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/java/se/sundsvall/checklist/service/util/VerificationUtils.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/api/model/CustomTaskCreateRequestTest.java
src/test/java/se/sundsvall/checklist/api/model/CustomTaskUpdateRequestTest.java
src/test/java/se/sundsvall/checklist/api/validation/impl/RoleTypeSubsetConstraintValidatorTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/SortorderServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/java/se/sundsvall/checklist/service/util/VerificationUtilsTest.java
src/test/resources/api/openapi.yaml
src/test/resources/db/scripts/employeeChecklistIT-testdata.sql

- Adjusted sort functionality to use an accumulated list of sort entries from starting point to root level in the organization structure instead of just using the closest matching list of sort entries
- Added new attribute, roleType, to request for creating and updating custom tasks, plus a validator for validating that correct value is used
- Made response from initialization of employee onboardings more informative
- Updated IT-tests to verify inheritance of custom sort

UF-14495: Adjusted sort functionality and added API attribute

---

src/integration-test/resources/DelegationIT/__files/shared/responses/api-mdviewer-get-company-response.json
src/integration-test/resources/DelegationIT/__files/test2_fetchDelegatedEmployeeChecklists/mappings/api-mdviewer-get-company.json
src/main/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepository.java
src/main/java/se/sundsvall/checklist/service/DelegationService.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/TaskService.java
src/main/java/se/sundsvall/checklist/service/util/ChecklistUtils.java
src/test/java/se/sundsvall/checklist/service/DelegationServiceTest.java
src/test/java/se/sundsvall/checklist/service/TaskServiceTest.java
src/test/java/se/sundsvall/checklist/service/util/ChecklistUtilsTest.java
src/test/resources/db/scripts/delegationIT-testdata.sql

- Added filtering of obsolete tasks and phases when fetching delegated checklists
- Added initialization of tasks when fetching delegated checklists
- Applied sorting of tasks and phases when fetching delegated checklists
- Extended logic to also remove fulfilment statuses referring to a task upon task deletion

UF-14520: Synchronized logic when fetching checklists

---

src/main/resources/contracts/messaging/messaging.yaml

UF-14622: Update to messaging 6.1

---

src/main/java/se/sundsvall/checklist/integration/employee/EmployeeFilterBuilder.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/util/VerificationUtils.java

Added two more valid employment form ids

---

src/main/java/se/sundsvall/checklist/service/CommunicationService.java
src/main/java/se/sundsvall/checklist/service/scheduler/ManagerEmailScheduler.java
src/test/java/se/sundsvall/checklist/service/CommunicationServiceTest.java

- Added transactional to execute method
- Added log row when email is being sent

UF-15240: Added transactional to execute method

---

src/main/java/se/sundsvall/checklist/service/DelegationService.java
src/test/java/se/sundsvall/checklist/service/DelegationServiceTest.java

- Fixed NPE when updated attribute is null for checklist entity

UF-15815: Fixed bug in code where null value was not handled

---

README.md
src/integration-test/resources/EmployeeChecklistIT/__files/test14_initializeEmployeeChecklists/mappings/api-employee-new-employments.json

- Adjusted regex for month value
- Updated readme

UF-16338: Fixed failing IT-test

---

pom.xml
src/main/java/se/sundsvall/checklist/api/EmployeeChecklistResource.java
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepository.java
src/main/java/se/sundsvall/checklist/service/EmployeeChecklistService.java
src/main/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapper.java
src/main/java/se/sundsvall/checklist/service/util/StringUtils.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceFailureTest.java
src/test/java/se/sundsvall/checklist/api/EmployeeChecklistResourceTest.java
src/test/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegrationTest.java
src/test/java/se/sundsvall/checklist/integration/db/repository/EmployeeChecklistRepositoryTest.java
src/test/java/se/sundsvall/checklist/service/EmployeeChecklistServiceTest.java
src/test/java/se/sundsvall/checklist/service/mapper/EmployeeChecklistMapperTest.java
src/test/java/se/sundsvall/checklist/service/util/StringUtilsTest.java
src/test/resources/api/openapi.yaml

- Added possibility to update manager connected to the employee for all ongoing checklists where information is out of date
- Added possibility to update manager for a specific employee, independent of if the checklist is ongoing or not

HYDRAN-85: Extended logic for updating manager of an employee

---

src/integration-test/java/apptest/EmployeeChecklistIT.java
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-bemp0loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-cman1agr.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-lemp6loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-memp6loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-nemp6loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-employee-employments-oemp6loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/mappings/api-gateway-token.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-bemp0loyee-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-cman1agr-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-lemp6loyee-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-memp6loyee-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-nemp6loyee-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test27_updateManagerOnOngoingChecklists/responses/api-employee-employments-oemp6loyee-response.json
src/integration-test/resources/EmployeeChecklistIT/__files/test28_updateManagerForSpecificEmployee/expected.json
src/integration-test/resources/EmployeeChecklistIT/__files/test28_updateManagerForSpecificEmployee/mappings/api-employee-employments-bemp0loyee.json
src/integration-test/resources/EmployeeChecklistIT/__files/test28_updateManagerForSpecificEmployee/mappings/api-gateway-token.json
src/integration-test/resources/EmployeeChecklistIT/__files/test28_updateManagerForSpecificEmployee/responses/api-employee-employments-bemp0loyee-response.json
src/main/java/se/sundsvall/checklist/integration/db/EmployeeChecklistIntegration.java
src/main/java/se/sundsvall/checklist/service/mapper/OrganizationMapper.java

HYDRAN-100: Added IT-test for manager update
